services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - D:/database/postgres/container-data:/var/lib/postgresql/data
      - D:/database/postgres/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - ${POSTGRES_DATA}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
