services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    profiles:
      - postgres
    env_file:
      - .env
    volumes:
      - D:/database/postgres/container-data:/var/lib/postgresql/data
      - D:/database/postgres/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - ${POSTGRES_DATA:-}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - database-network
  pgadmin:
    image: dpage/pgadmin4:9.8.0
    container_name: pgadmin
    ports:
      - "8888:80"
    profiles:
      - pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_USER}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
    networks:
      - database-network

networks:
  database-network:
    driver: bridge